; LogFire Example Project
; Build all:    pio run
; Build one:    pio run -e esp32
; Upload:       pio run -e esp32 -t upload

[platformio]
default_envs = esp32   ; change to esp8266 when needed

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../..
build_flags =
    -D USE_ESP32

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../..
build_flags =
    -D USE_ESP8266
